{
 "title": "Distributed Rate Limiter",
 "refresh": "5s",
 "panels": [
  {
   "title": "Allowed Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(rate_limiter_requests_allowed_total[1m]))"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(rate_limiter_requests_blocked_total[1m]))"
    }
   ]
  },
  {
   "title": "Redis Up",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 5 },
   "targets": [
    { "expr": "rate_limiter_redis_up" }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rate_limiter_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}